### ISSUE TITLE
Serialized data overflow

### ISSUE THREAD

**Issue by subdesign** [mikemand/logviewer#80]
I add an issue because of the Pull Request is disabled. If I log serialized data, the lines are overflown, out of the screen. Adding the following css rule to the _style.css_ solves the problem:

``` css
.stack-header 
{
    word-wrap: break-word;
}
```
